### ISSUE TITLE
Docs aktualisieren

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/redaxo.docset#1]
Um dieses repos nützlich zu halten für verwender, wäre es nötig es von zeit zu zeit zu aktualisieren.

Dazu wäre es gut wenn wir eine anleitung hier im repos hätten, wie man die inhalte generieren muss.

**Comment by staabm** [comment]
@gorkarod könntest du dokumentieren wie du das in der Vergangenheit gemacht hast?

**Comment by gorkarod** [comment]
Habe das Dokset aktualisiert und habe das Readme um eine kurze Anleitung ergänzt. Wie bekomme ich mit, dass die Doku aktualisiert wurde?

**Comment by staabm** [comment]
Danke Dir. 

Du könntest zum Beispiel des doku repo beobachten
https://github.com/redaxo/docs

**Comment by gorkarod** [comment]
Stimmt :-) Danke
